### ISSUE TITLE
branchEnv and buildNoEnv use default values although there are values redefined in the .testrailrc config file

### ISSUE THREAD

**Issue by jaredpraino-okta** [DamianOsipiuk/testcafe-reporter-testrail#11]
Here is what my config file for .testrailrc looks like:
```
{
    "enabled": true,
    "host": "https://<REDACTED>.testrail.net",
    "user": "<REDACTED>",
    "apiKey": "<REDACTED>",
    "projectId": "P25",
    "suiteId": "S29",
    "branchEnv": "Develop",
    "runName": "%BRANCH%: - %DATE%",
    "dateFormat": "YYYY-MM-DD"
}
```

However, after successfully creating a testrail run which contains expected results, the name of the report is `master: - 2020-08-06`

Inside of `node_modules/testcafe-reporter-testrail/lib/index.js` I changed lines 239, 240 from
```
this.branch = process.env[this.config.branchEnv] || "master";
this.buildNo = process.env[this.config.buildNoEnv] || "unknown";
```
to
```
this.branch = this.config.branchEnv || "master";
this.buildNo = this.config.buildNoEnv || "unknown";
```
and now I am getting the expected test run name: `Develop: - 2020-08-06`.

Please let me know if I missed something, thanks!

**Comment by DamianOsipiuk** [comment]
Hi @jaredpraino-okta. You are using wrong property for what you want to achieve.
You should modify `runName` if the branch is static. Ex. `"runName": "Develop: - %DATE%",`

`branchEnv` controls which environment variable should be read to get the branch name. It's useful when you are running tests for multiple branches.
IE. When you set `branchEnv` to `FOO` then this will be read from env to get the branch name. You can set it before script execution like `FOO=Develop testcafe ...`

I hope this makes it more clear

**Comment by jaredpraino-okta** [comment]
Hi @DamianOsipiuk thank you for the quick response.  That does make it clearer.  With our implementation, we are trying to execute our testcafe tests with different configurations.  The idea was to use ENV vars to give the two tests runs unique names.  We would like `runName` to be dynamic such that we could pass a name in, say "Develop" or "Develop 2".

So in our case, should we leave `branchEnv` alone, and then in the shell command to start testcafe include `BRANCH=Develop`?

**Comment by DamianOsipiuk** [comment]
@jaredpraino-okta That is correct. Same thing applies for build number.
You can also set ENV variables for whole session not only one commmand, but for each operating system syntax can be slightly different. (Windows mainly)

**Comment by jaredpraino-okta** [comment]
Perfect, thank you!
