### ISSUE TITLE
Why do we use .testrailrc instead of dotenv file?

### ISSUE THREAD

**Issue by Scot3004** [DamianOsipiuk/testcafe-reporter-testrail#12]
Hello
I'm here again 

I have a question for you, why we use here a `.testrailrc` file instead a more common `.env` file to load the configurations?

something like that https://www.npmjs.com/package/dotenv. I found this useful for something that I'm doing

**Comment by DamianOsipiuk** [comment]
Hi, You can use dotenv with the plugin without any code changes.
Since plugin works by using both ENV variables and config file, you can use whichever works better for you.

Check https://www.npmjs.com/package/dotenv#preload to preload .env file, which then would be picked up by testrail plugin.

**Comment by Scot3004** [comment]
yes, you're right, but with this approach I found a problem:
If the user has not a .testrailrc file then an error is thrown because the package tries to get this file.
a workaround for it is to create a .testrailrc file empty something like
`echo "{}" > .testrailrc`
in the repo that uses this project

**Comment by DamianOsipiuk** [comment]
Well, then it's a bug and needs to be fixed :D
Thanks for reporting.

**Comment by DamianOsipiuk** [comment]
@Scot3004 Fixed in https://github.com/DamianOsipiuk/testcafe-reporter-testrail/releases/tag/v0.6.2
