### ISSUE TITLE
Testrail getRuns hide API errors

### ISSUE THREAD

**Issue by Scot3004** [DamianOsipiuk/testcafe-reporter-testrail#5]
# Actual behavior
When I try to get the runs of my TestRail instance 
And I have errors in my credentials
Then the error
`[TestRail] Sending report to TestRail failed TypeError: runs.find is not a function is displayed` is raised

# Expected behavior
The error message should explicit tell me that my credentials are wrong, for example `[TestRail] Sending report to TestRail failed Authentication failed: invalid or missing user/password or session cookie.`

# Diagnostic
the line https://github.com/DamianOsipiuk/testcafe-reporter-testrail/blob/026d786612a548bdcf26a4c0b2694d5248776206/src/index.ts#L198
ignores that the response has errors
```json
{
  "error": "Authentication failed: invalid or missing user/password or session cookie."
}
```
after it tries to find over an inexistent array, the body is an object

**Comment by DamianOsipiuk** [comment]
@Scot3004 Thanks for reporting the issue.
Error handling is not the strongest point of this library. I will try to improve it in the next version.

**Comment by Scot3004** [comment]
I can work on it, I already created a method validateConfig, but now I'm facing that, there's not test runner so I cannot write unit tests for my code. Which test runner do you think should I use?, or wanna review it without tests (not recommended)

**Comment by DamianOsipiuk** [comment]
@Scot3004 Errors should be now properly reported in v0.6.0
