### ISSUE TITLE
question? possibility to use node 10

### ISSUE THREAD

**Issue by Scot3004** [DamianOsipiuk/testcafe-reporter-testrail#6]
Hello, I'm trying to use your library but I know that you dropped the support for node < 12 after this commit https://github.com/DamianOsipiuk/testcafe-reporter-testrail/commit/a533c0426ee05c0050e54f11b77edacca92494f2

Is there any possibility to change the minimum version to node 10 or there's any technical reason that I'm ignoring about this change.

**Comment by DamianOsipiuk** [comment]
@Scot3004 It should just work. I marked this for node 12 as I had no setup to test it properly for node 10.
I will test it out and try to lower down the required node version.

**Comment by DamianOsipiuk** [comment]
@Scot3004 Lowered required version of node since it's working properly on node v10.13.
