### ISSUE TITLE
Feature request: Find run but if no exists throw an Error

### ISSUE THREAD

**Issue by Scot3004** [DamianOsipiuk/testcafe-reporter-testrail#8]
I like the work that you did for the error handling, I'm thinking in the following scenario:
What if the user don't want to create test runs automatically instead of, he want to control when a new run is created maybe for reporting or something.

Im thinking in the next scenarios:

Scenarion 1: (this is already covered, i think a testcase should be created)
Given a user that wants to use a existing run
When the user send the name parameter, and a parameter for no test creation
Then the test reports uses the test run found by name that is currently active

Scenarion 2: (this is new)
Given a user that wants to run a existing run
When the user send the name parameter, and a parameter for no test creation
And The test run doesn't exists in testrail
Then the test report is not sent
And a error is displayed seing that the testrun not exists

**Comment by Scot3004** [comment]
For each test run a new run is created but that I wanted is to use the same run
![imagen](https://user-images.githubusercontent.com/1175402/86949818-d7aa7280-c114-11ea-9ac2-545c06ef27b3.png)

**Comment by DamianOsipiuk** [comment]
Currently when a `refs` property match and the run is not yet closed it will be updated with the current results.
To set that property you could use the TESTRAIL_REFERENCE env variable.

I think what you want to achieve is kind of re-run the tests functionality. For that I think the best would be to provide test run id beforehand as additional property.
This will indicate that you know the ID and want to update specific test run.

However I think that another piece that cannot be covered by a reporter plugin needs to be controlled. You actually would want to run the same set of tests as before.
For that some kind of test runner could be created that will fetch the test run results and run only the same set of tests with testcafe.

**Comment by Scot3004** [comment]
Actually I no yet understand exactly how works the ref property, sorry for that

For the re run functionality you're right because i want to have a run for the current sprint

agree with you, the last part cannot be covered by a reporter, and that's why I'm trying to create the runs manually, gives a little bit more control,
so, do you agree if I send a pr by getting this run id from config if exists, else maintain current behavior of get the tests run.
All in a new method called getRunFromConfig or something like that

**Comment by Scot3004** [comment]
I get you, TESTRAIL_REFERENCE in the below example should be "Testrail integration testrail", in other words the same name used for TESTRAIL_RUN_NAME

**Comment by DamianOsipiuk** [comment]
Not exactly. Reference is another field and can be any string you want. When you create a run manually you can fill the reference field in TestRail also. It suppose to be used as a link field I believe.

This is not a built in mechanism. I put it in place to integrate two plugins together that should store data in the same test run. I did not want to match the runs by the name since my names are generated with the timestamp which would not match.

You can submit a MR with the run id override.

**Comment by Scot3004** [comment]
Hello @DamianOsipiuk  have you any concern if I extract some methods to a new file, I cannot access to the non exported methods in jest and I want to increase coverage not reduce your current coverage

**Comment by DamianOsipiuk** [comment]
Do not worry about coverage, i have to add many tests anyway.
Also i'm rather following concept of testing only public functions and methods, not artificially exposing internals for test purposes.
